# Generated by Django 3.0.5 on 2021-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('hash', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('pdf_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pdf Path')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
