# Generated by Django 3.0.5 on 2021-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Url')),
                ('project_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project id')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('aka_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aka Title')),
                ('project_type', models.CharField(blank=True, max_length=200, null=True)),
                ('project_issue_date', models.CharField(blank=True, max_length=200, null=True)),
                ('project_issue_date1', models.CharField(blank=True, max_length=200, null=True)),
                ('project_start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('project_update', models.CharField(blank=True, max_length=200, null=True)),
                ('locations', models.CharField(blank=True, max_length=200, null=True)),
                ('photography_start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('writers', models.CharField(blank=True, max_length=200, null=True)),
                ('directors', models.CharField(blank=True, max_length=200, null=True)),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('producers', models.CharField(blank=True, max_length=200, null=True)),
                ('production_companies', models.CharField(blank=True, max_length=200, null=True)),
                ('studios', models.CharField(blank=True, max_length=200, null=True)),
                ('plot', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('project_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.CharField(blank=True, max_length=200, null=True)),
                ('start_wrap_schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_num', models.CharField(blank=True, max_length=200, null=True)),
                ('listing', models.CharField(blank=True, max_length=200, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=200, null=True)),
                ('letter_creation_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
